import fs from 'fs';
import {
  INITIAL_SITE_SETTINGS,
  INITIAL_HOMEPAGE_CONFIG,
  INITIAL_ABOUT_SETTINGS,
  INITIAL_HEADER_SETTINGS,
  INITIAL_FOOTER_SETTINGS,
  INITIAL_SOCIAL_LINKS,
  INITIAL_VOLUNTEER_SETTINGS,
  INITIAL_SUPPORT_SETTINGS,
  INITIAL_CONTACT_SETTINGS,
  INITIAL_SEO_SETTINGS,
  INITIAL_NAVIGATION_ITEMS,
  INITIAL_BANNERS,
  INITIAL_MEDIA_LIBRARY,
  INITIAL_GALLERY_ALBUMS,
  INITIAL_PRESS_COVERAGE,
  INITIAL_ADMIN_PROFILES,
  INITIAL_CAMPAIGNS,
  INITIAL_PROGRAMS,
  INITIAL_IMPACT_METRICS,
  INITIAL_IMPACT_STORIES,
  INITIAL_NEWS,
  INITIAL_EVENTS,
  INITIAL_GALLERY,
  INITIAL_VIDEOS,
  INITIAL_REPORTS,
  INITIAL_PARTNERS,
  INITIAL_VOLUNTEER_APPLICATIONS,
  INITIAL_DONATIONS,
  INITIAL_FAQS,
  INITIAL_COMMITTEES,
  INITIAL_PERSONS,
  INITIAL_POSITIONS,
  INITIAL_COMMITTEE_MEMBERS
} from '../src/data/initialData';

const fullData = {
  version: '2.1.0',
  exportedAt: new Date().toISOString(),
  organization: 'Infinity Bangladesh',
  slogan: 'United for Humanity',
  settings: INITIAL_SITE_SETTINGS,
  homepageConfig: INITIAL_HOMEPAGE_CONFIG,
  aboutSettings: INITIAL_ABOUT_SETTINGS,
  headerSettings: INITIAL_HEADER_SETTINGS,
  footerSettings: INITIAL_FOOTER_SETTINGS,
  socialLinks: INITIAL_SOCIAL_LINKS,
  volunteerSettings: INITIAL_VOLUNTEER_SETTINGS,
  supportSettings: INITIAL_SUPPORT_SETTINGS,
  contactSettings: INITIAL_CONTACT_SETTINGS,
  seoSettings: INITIAL_SEO_SETTINGS,
  navigationItems: INITIAL_NAVIGATION_ITEMS,
  banners: INITIAL_BANNERS,
  mediaLibrary: INITIAL_MEDIA_LIBRARY,
  galleryAlbums: INITIAL_GALLERY_ALBUMS,
  pressCoverages: INITIAL_PRESS_COVERAGE,
  adminProfiles: INITIAL_ADMIN_PROFILES,
  campaigns: INITIAL_CAMPAIGNS,
  programs: INITIAL_PROGRAMS,
  metrics: INITIAL_IMPACT_METRICS,
  stories: INITIAL_IMPACT_STORIES,
  news: INITIAL_NEWS,
  events: INITIAL_EVENTS,
  gallery: INITIAL_GALLERY,
  videos: INITIAL_VIDEOS,
  reports: INITIAL_REPORTS,
  partners: INITIAL_PARTNERS,
  volunteers: INITIAL_VOLUNTEER_APPLICATIONS,
  donations: INITIAL_DONATIONS,
  messages: [],
  faqs: INITIAL_FAQS,
  committees: INITIAL_COMMITTEES,
  persons: INITIAL_PERSONS,
  positions: INITIAL_POSITIONS,
  committeeMembers: INITIAL_COMMITTEE_MEMBERS
};

const jsonString = JSON.stringify(fullData, null, 2);
fs.writeFileSync('public/infinity-bangladesh-data.json', jsonString, 'utf8');
fs.writeFileSync('docs/infinity-bangladesh-data.json', jsonString, 'utf8');
console.log('✓ Successfully exported fresh JSON with updated metrics to public/ and docs/');
